-- I. CREATE TABLES + SEQUENCES + INDEX 
-- -------------------------------------- 
-- Tạo SEQUENCE cho khóa chính 
CREATE SEQUENCE SEQ_PHIM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PHONG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GHE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SUAT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_KHACH START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DATCHO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TTOAN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NV START WITH 1 INCREMENT BY 1 NOCACHE;


-- 1. Bảng PHIM
CREATE TABLE PHIM (
    MA_PHIM VARCHAR2(10) PRIMARY KEY,
    TEN_PHIM VARCHAR2(100) NOT NULL,
    THE_LOAI VARCHAR2(50),
    THOI_LUONG NUMBER(3),
    MOTA CLOB,
    TRAILER VARCHAR2(255),
    HINH_ANH VARCHAR2(255)
);

-- 2. Bảng PHONG_CHIEU
CREATE TABLE PHONG_CHIEU (
    MA_PHONG VARCHAR2(10) PRIMARY KEY,
    TEN_PHONG VARCHAR2(50) NOT NULL,
    SO_HANG NUMBER(2) NOT NULL,
    SO_COT NUMBER(2) NOT NULL
);

-- 3. Bảng GHE
CREATE TABLE GHE (
    MA_GHE VARCHAR2(10) PRIMARY KEY,
    MA_PHONG VARCHAR2(10),
    HANG CHAR(1),
    COT NUMBER(2),
    LOAI_GHE VARCHAR2(10) CHECK (LOAI_GHE IN ('Thuong', 'VIP', 'Doi')),
    TRANG_THAI VARCHAR2(10) DEFAULT 'Trong' CHECK (TRANG_THAI IN ('Trong', 'Da dat', 'Bao tri')),
    FOREIGN KEY (MA_PHONG) REFERENCES PHONG_CHIEU(MA_PHONG)
);

-- 4. Bảng SUAT_CHIEU
CREATE TABLE SUAT_CHIEU (
    MA_SUAT VARCHAR2(10) PRIMARY KEY,
    MA_PHIM VARCHAR2(10),
    MA_PHONG VARCHAR2(10),
    NGAY_CHIEU DATE,
    GIO_CHIEU VARCHAR2(5), -- Ví dụ: '19:00'
    FOREIGN KEY (MA_PHIM) REFERENCES PHIM(MA_PHIM),
    FOREIGN KEY (MA_PHONG) REFERENCES PHONG_CHIEU(MA_PHONG)
);

-- 5. Bảng GIA_GHE (áp dụng cho từng suất chiếu)
CREATE TABLE GIA_GHE (
    MA_SUAT VARCHAR2(10),
    LOAI_GHE VARCHAR2(10),
    GIA NUMBER(10),
    PRIMARY KEY (MA_SUAT, LOAI_GHE),
    FOREIGN KEY (MA_SUAT) REFERENCES SUAT_CHIEU(MA_SUAT),
    CHECK (LOAI_GHE IN ('Thuong', 'VIP', 'Doi'))
);

-- 6. Bảng KHACH_HANG
CREATE TABLE KHACH_HANG (
    MA_KH VARCHAR2(10) PRIMARY KEY,
    TEN_KH VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    SDT VARCHAR2(15),
    MAT_KHAU VARCHAR2(100),
    DIA_CHI VARCHAR2(255)
);

-- 7. Bảng DAT_CHO
CREATE TABLE DAT_CHO (
    MA_DAT VARCHAR2(10) PRIMARY KEY,
    MA_KH VARCHAR2(10),
    MA_SUAT VARCHAR2(10),
    MA_GHE VARCHAR2(10),
    NGAY_DAT DATE DEFAULT SYSDATE,
    FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
    FOREIGN KEY (MA_SUAT) REFERENCES SUAT_CHIEU(MA_SUAT),
    FOREIGN KEY (MA_GHE) REFERENCES GHE(MA_GHE)
);

-- 8. Bảng THANH_TOAN
CREATE TABLE THANH_TOAN (
    MA_THANH_TOAN VARCHAR2(10) PRIMARY KEY,
    MA_DAT VARCHAR2(10),
    PHUONG_THUC VARCHAR2(20) CHECK (PHUONG_THUC IN ('Online', 'Tien mat', 'Chuyen khoan')),
    TONG_TIEN NUMBER(10),
    NGAY_THANH_TOAN DATE DEFAULT SYSDATE,
    FOREIGN KEY (MA_DAT) REFERENCES DAT_CHO(MA_DAT)
);

CREATE TABLE NHAN_VIEN (
    MA_NV VARCHAR2(10) PRIMARY KEY,
    TEN_NV VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    SDT VARCHAR2(15),
    MAT_KHAU VARCHAR2(100),
    CHUC_VU VARCHAR2(30),  -- VD: QuanLy, BanVe
    NGAY_VAO_LAM DATE,
    LUONG NUMBER(10)
);

CREATE OR REPLACE TRIGGER TRG_PHIM_ID
BEFORE INSERT ON PHIM
FOR EACH ROW
BEGIN
  :NEW.MA_PHIM := 'P' || LPAD(SEQ_PHIM.NEXTVAL, 6, '0');
END;

CREATE OR REPLACE TRIGGER TRG_PHONG_ID
BEFORE INSERT ON PHONG_CHIEU
FOR EACH ROW
BEGIN
  :NEW.MA_PHONG := 'R' || LPAD(SEQ_PHONG.NEXTVAL, 4, '0');
END;

CREATE OR REPLACE TRIGGER TRG_GHE_ID
BEFORE INSERT ON GHE
FOR EACH ROW
BEGIN
  :NEW.MA_GHE := 'G' || LPAD(SEQ_GHE.NEXTVAL, 5, '0');
END;

CREATE OR REPLACE TRIGGER TRG_SUAT_ID
BEFORE INSERT ON SUAT_CHIEU
FOR EACH ROW
BEGIN
  :NEW.MA_SUAT := 'S' || LPAD(SEQ_SUAT.NEXTVAL, 6, '0');
END;

CREATE OR REPLACE TRIGGER TRG_KHACH_ID
BEFORE INSERT ON KHACH_HANG
FOR EACH ROW
BEGIN
  :NEW.MA_KH := 'KH' || LPAD(SEQ_KHACH.NEXTVAL, 5, '0');
END;

CREATE OR REPLACE TRIGGER TRG_DATCHO_ID
BEFORE INSERT ON DAT_CHO
FOR EACH ROW
BEGIN
  :NEW.MA_DAT := 'DC' || LPAD(SEQ_DATCHO.NEXTVAL, 6, '0');
END;

CREATE OR REPLACE TRIGGER TRG_TTOAN_ID
BEFORE INSERT ON THANH_TOAN
FOR EACH ROW
BEGIN
  :NEW.MA_THANH_TOAN := 'TT' || LPAD(SEQ_TTOAN.NEXTVAL, 6, '0');
END;

CREATE OR REPLACE TRIGGER TRG_NV_ID
BEFORE INSERT ON NHAN_VIEN
FOR EACH ROW
BEGIN
  :NEW.MA_NV := 'NV' || LPAD(SEQ_NV.NEXTVAL, 5, '0');
END;

-- Thêm chỉ mục để tối ưu
-- Bảng PHIM: Tìm kiếm phim theo tên
CREATE INDEX idx_phim_ten ON PHIM(TEN_PHIM);

-- Bảng SUAT_CHIEU: Tìm suất chiếu theo ngày và giờ
CREATE INDEX idx_suatchieu_ngaygio ON SUAT_CHIEU(NGAY_CHIEU, GIO_CHIEU);

-- Bảng SUAT_CHIEU: Tìm suất chiếu theo mã phòng
CREATE INDEX idx_suatchieu_phong ON SUAT_CHIEU(MA_PHONG);

-- Bảng GHE: Tìm ghế theo mã phòng (khi hiển thị sơ đồ ghế)
CREATE INDEX idx_ghe_phong ON GHE(MA_PHONG);

-- Bảng GIA_GHE: Tìm giá ghế theo suất chiếu
CREATE INDEX idx_giaghe_suat ON GIA_GHE(MA_SUAT);

-- Bảng DAT_CHO: Tìm đặt chỗ theo mã khách hàng
CREATE INDEX idx_datcho_kh ON DAT_CHO(MA_KH);

-- Bảng DAT_CHO: Tìm đặt chỗ theo suất chiếu
CREATE INDEX idx_datcho_suat ON DAT_CHO(MA_SUAT);

-- Bảng THANH_TOAN: Tìm thanh toán theo phương thức
CREATE INDEX idx_thanhtoan_phuongthuc ON THANH_TOAN(PHUONG_THUC);

-- Bảng KHACH_HANG: Tìm khách hàng theo email
CREATE INDEX idx_khachhang_email ON KHACH_HANG(EMAIL);



