/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.phim.component;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class Sidebar extends javax.swing.JPanel 
{

    private PhimSelectionListener phimListener;
    public interface PhimSelectionListener {
        void onPhimSelected(String phimKey);
    }


    public Sidebar() {
        setOpaque(false);
        initComponents();      
    }


public void setPhimSelectionListener(PhimSelectionListener listener) {
    this.phimListener = listener;
}
@Override
public void addNotify() {
    super.addNotify();
   
}

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        GradientPaint gradient = new GradientPaint(
            0, 0, new Color(255, 65, 108),    // #FF416C
            0, getHeight(), new Color(255, 75, 43)  // #FF4B2B
        );
        g2d.setPaint(gradient);
        g2d.fillRect(0, 0, getWidth(), getHeight());
    }

  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupMenu = new javax.swing.ButtonGroup();
        jbtnDashboard = new javax.swing.JToggleButton();
        jbtnEmployee = new javax.swing.JToggleButton();
        jbtnPhim = new javax.swing.JToggleButton();
        jbtnStock1 = new javax.swing.JToggleButton();
        btnSC = new javax.swing.JButton();

        btngroupMenu.add(jbtnDashboard);
        jbtnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard.png"))); // NOI18N
        jbtnDashboard.setText("Dashboard");
        jbtnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDashboardActionPerformed(evt);
            }
        });

        btngroupMenu.add(jbtnEmployee);
        jbtnEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NhanVien.png"))); // NOI18N
        jbtnEmployee.setText("Nhân viên");
        jbtnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmployeeActionPerformed(evt);
            }
        });

        btngroupMenu.add(jbtnPhim);
        jbtnPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phim.png"))); // NOI18N
        jbtnPhim.setText("Phim");
        jbtnPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPhimActionPerformed(evt);
            }
        });

        btngroupMenu.add(jbtnStock1);
        jbtnStock1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnStock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HoaDon.png"))); // NOI18N
        jbtnStock1.setText("Hóa đơn");
        jbtnStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStock1ActionPerformed(evt);
            }
        });

        btnSC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suất chiếu.png"))); // NOI18N
        btnSC.setText("Suất chiếu ");
        btnSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtnStock1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jbtnDashboard)
                .addGap(35, 35, 35)
                .addComponent(jbtnPhim)
                .addGap(43, 43, 43)
                .addComponent(jbtnEmployee)
                .addGap(44, 44, 44)
                .addComponent(jbtnStock1)
                .addGap(41, 41, 41)
                .addComponent(btnSC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPhimActionPerformed
        if (phimListener != null) phimListener.onPhimSelected("PHIM");

    }//GEN-LAST:event_jbtnPhimActionPerformed

    private void jbtnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDashboardActionPerformed
        if (phimListener != null) phimListener.onPhimSelected("DASHBOARD");
    }//GEN-LAST:event_jbtnDashboardActionPerformed

    private void jbtnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmployeeActionPerformed
        if (phimListener != null) phimListener.onPhimSelected("EMPLOYEE");
    }//GEN-LAST:event_jbtnEmployeeActionPerformed

    private void jbtnStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStock1ActionPerformed
               if (phimListener != null) phimListener.onPhimSelected("HOADON");
 // TODO add your handling code here:
    }//GEN-LAST:event_jbtnStock1ActionPerformed

    private void btnSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSCActionPerformed
               if (phimListener != null) phimListener.onPhimSelected("SUATCHIEU");
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnSCActionPerformed

       @Override
    public Dimension getPreferredSize() {
        return new Dimension(200, getParent() != null ? getParent().getHeight() : 600);

    }

    @Override
    public void doLayout() {
        super.doLayout();
        revalidate();
        repaint();
    }
   private void resizeButtons() {
        int totalHeight = getHeight();
        int buttonCount = 5;
        int margin = 10;
        int availableHeight = totalHeight - (margin * (buttonCount + 1));
        int buttonHeight = availableHeight / buttonCount;

        JToggleButton[] buttons = {
            jbtnDashboard, jbtnPhim, jbtnEmployee, 
        };

        for (JToggleButton btn : buttons) {
            btn.setPreferredSize(new Dimension(getWidth() - 20, buttonHeight));
            btn.setMaximumSize(new Dimension(getWidth() - 20, buttonHeight));
            btn.setMinimumSize(new Dimension(getWidth() - 20, buttonHeight));
            btn.setFont(new Font("Segoe UI", Font.BOLD, Math.max(12, buttonHeight / 4)));
        }
        revalidate();
        repaint();
    }
   
        private void onMenuSelected(String key) {
           if (phimListener != null) {
               phimListener.onPhimSelected(key);
           }
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSC;
    private javax.swing.ButtonGroup btngroupMenu;
    private javax.swing.JToggleButton jbtnDashboard;
    private javax.swing.JToggleButton jbtnEmployee;
    private javax.swing.JToggleButton jbtnPhim;
    private javax.swing.JToggleButton jbtnStock1;
    // End of variables declaration//GEN-END:variables
}
